server:
  port: 9091

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    数据库中下划线命名 工程中驼峰命名
    map-underscore-to-camel-case: true

#mapper文件所在处
  mapper-locations: classpath:mapper/*.xml

#存文件的基地址
fileBaseUrl: http://localhost:${server.port}